version: 0.2

phases:
  install:
    commands:
      - echo Installing Trivy for Container Scanning...
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.48.3/trivy_0.48.3_Linux-64bit.tar.gz
      - tar -zxvf trivy_0.48.3_Linux-64bit.tar.gz
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Pulling the Docker image...
      - docker pull $REPOSITORY_URI:$IMAGE_TAG
      - echo Running Trivy vulnerability scanner in CI mode...
      - ./trivy image --no-progress --exit-code 1 --severity CRITICAL,HIGH $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Scan completed successfully.
artifacts:
  files:
    - imagedefinitions.json
