version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Pulling the Docker image to scan...
      - docker pull $REPOSITORY_URI:$IMAGE_TAG
      - echo Running Trivy vulnerability scanner via Docker...
      - docker run --rm
        -v /var/run/docker.sock:/var/run/docker.sock
        public.ecr.aws/aquasecurity/trivy:latest
        image --no-progress --exit-code 1 --severity CRITICAL,HIGH
        $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Scan completed.
artifacts:
  files:
    - "**/*"
  discard-paths: no
